### ISSUE TITLE
kodi v21 compatibility

### ISSUE THREAD

**Issue by menotuu** [RyanMelenaNoesis/XbmcSecurityCamOverlayAddOn#3]
Bekomme mit script.securitycam 1.6.1 unter Starting Kodi (21.0-RC2 (20.90.910) Git:20240318-c976aa91cd). Platform: webOS ARM 32

folgenden Fehler beim Starten des Addons.

Wie kann man das AddOn am besten direkt mit Kodi v22 kompatibel machen?

`2024-03-28 18:04:26.051 T:7504    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                   - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                  Error Type: <class 'TypeError'>
                                                  Error Contents: 'float' object cannot be interpreted as an integer
                                                  Traceback (most recent call last):
                                                    File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/script.securitycam/default.py", line 315, in <module>
                                                      camPreview = CamPreviewDialog(CAMERAS)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/script.securitycam/default.py", line 148, in __init__
                                                      self.cams[i]['control'] = xbmcgui.ControlImage(x, y, w, h, __loading__, aspectRatio = SETTINGS['aspectRatio'])
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                  TypeError: 'float' object cannot be interpreted as an integer
                                                  -->End of Python script error report<--
                                                  
2024-03-28 18:05:30.899 T:7615    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                   - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                  Error Type: <class 'TypeError'>
                                                  Error Contents: 'float' object cannot be interpreted as an integer
                                                  Traceback (most recent call last):
                                                    File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/script.securitycam/default.py", line 315, in <module>
                                                      camPreview = CamPreviewDialog(CAMERAS)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/script.securitycam/default.py", line 148, in __init__
                                                      self.cams[i]['control'] = xbmcgui.ControlImage(x, y, w, h, __loading__, aspectRatio = SETTINGS['aspectRatio'])
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                  TypeError: 'float' object cannot be interpreted as an integer
                                                  -->End of Python script error report<--`

**Comment by RyanMelenaNoesis** [comment]
I'm afraid I haven't used / updated this project in almost a decade.  I'm not currently using Kodi so it is unlikely I'll have the time to investigate this issue.  If you are able to troubleshoot and provide a pull request for a fix I'd be happy to accept it.
